### ISSUE TITLE
derivative of tanh seems to be wrong 

### ISSUE THREAD

**Issue by 404salad** [mathletedev/rust-ml#3]
shouldnt it be     derivative: &|x| 1/ 1+(x.powi(2)),

**Comment by neowsl** [comment]
I could be wrong, but from the various sources I used it seems like the derivative is `1 - tanh(x)^2`

https://blogs.cuit.columbia.edu/zp2130/derivative_of_tanh_function/

Have a wonderful day!

**Comment by neowsl** [comment]
*Also, did you mean to write "1 / 1" + (x.powi(2))? The 1/1 evaluates to 1 before the addition

**Comment by 404salad** [comment]
I am so sorry i misunderstood hyperbolic tan as arctan
PSi loved the video and got to learn a lot from it!
