### ISSUE TITLE
Derivative of Sigmoid activation is incorrect

### ISSUE THREAD

**Issue by DamonPalovaara** [mathletedev/rust-ml#5]
First I want to address that the actual function name is the Logistics function which is a member of the class of sigmoid functions. When I refer to the Logistics function I'm talking about your sigmoid function.

x(1-x) is not the derivative of the Logistics function. It is easy to verify that fact by integrating x(1-x). The actual derivative of the Logistics function is f(x) * (1 - f(x)) where f(x) is the Logistics function.

I would have made a pull request but, given your current approach of implementing activations, I don't see a straight forward fix. However, there is a pull request that changed activations to traits. My suggestion is to merge that pull request first before addressing this issue.

Here is the section on the Logistics function derivative on Wikipedia:
https://en.wikipedia.org/wiki/Logistic_function#Derivative

**Comment by neowsl** [comment]
Thanks for the info! You're right, but in this case, `x` _represents_ `f(x)`, as it is the result of the initial forward pass. I should have given the variable a better name.
If this logic is wrong, do let me know!
